version: "2"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE= test
      - MYSQL_ROOT_PASSWORD=password
  webserver:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=sa
