version: "2"
services: 
   mysql-standalone:
    image: mysql
    container_name: mysql-standalone
    ports:
      - "3306:3306"
    environment:
    - MYSQL_USER=sa
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE= test
    - MYSQL_ROOT_PASSWORD=password
   webserver:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - mysql-standalone
